project:
  type: book
  output-dir: docs

book:
  title: "The Life of Saint Mary the Egyptian: Toward a Digital Critical Edition of the Old French Version T with English Translations"
  author:
    - name: "Loren Easterday Lee"
      affiliation: 
        name: "Department of French, University of Virginia"
  date: "06/30/2025"
  date-format: long
  chapters:
    - index.qmd
    - abstract.qmd
    - acknowledgements.qmd
    - intro.qmd
    - chapter1.qmd
    - chapter2-1.qmd
    - chapter2-2.qmd
    - portraits.qmd
    - portraits-viz.qmd
    - chapter3.qmd
    - conclusion.qmd
    - appendix1.qmd
    - appendix2-intro.qmd
    - appendix2-T-A.qmd
    - appendix2-T-B.qmd
    - appendix2-T-C.qmd
    - appendix2-T-D.qmd
    - appendix2-T-E.qmd
    - appendix2-T-F1.qmd
    - appendix2-T-F2.qmd
    - references.qmd

bibliography: references.bib
csl: modern-language-association.csl

format:
  html:
    theme: cosmo
    number-sections: false
    toc: true
    toc-depth: 3
    toc-location: right
    toc-title: "Contents"
    toc-expand: 3
    css: styles.css
    grid:
      sidebar-width: 200px
      margin-width: 300px
    code-fold: true
    code-summary: "show the code"

  docx:
    toc: true



